backend:
  name: github
  repo: biopzhang/biopzhang.github.io
  branch: master

# Enable Local Backend to edit files on your hard drive directly
local_backend: true

# Publishing settings
media_folder: "assets/images"
public_folder: "/assets/images"

# The layout of the dashboard
collections:
  - name: "posts"
    label: "Posts & Resources (Bookmarks)"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Tags", name: "tags", widget: "string", required: false}
      - {label: "Categories", name: "categories", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "news"
    label: "News Announcements"
    folder: "_news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Inline", name: "inline", widget: "boolean", required: false, default: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}

  - name: "pages"
    label: "Static Pages (About, CV, etc)"
    folder: "_pages"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "string", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Description/Subtitle", name: "description", widget: "string", required: false}
      - {label: "Nav Checkbox", name: "nav", widget: "boolean", required: false}
      - {label: "Nav Order", name: "nav_order", widget: "number", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
